Реорганизация цифрового архива Сова Минервы включила в себя следующие этапы:

Механическое объединение архивов В.В.Файера и Н.В. Брагинской в одной директории.
Создание списка файлов, входящих в данный архив.
Выявление дубликатов видео (1 этап сверки (имя, размер)).
Выявление дубликатов видео (2 этап (сопоставление контрольных сумм файлов, Get-FileHash)).
Приведение файлов к единому формату данных (унификация видеоматериалов, перекодировка в формат MP4).
Создание отсутствующих расшифровок записей, их включение в архив.
...
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F3lDaHhpDcWnHIvGupHUiqY%2FUntitled%3Ftype%3Ddesign%26node-id%3D0%253A1%26mode%3Ddesign%26t%3DjTom5pk9M8IxGdaZ-1" allowfullscreen></iframe>
