Реорганизация цифрового архива Сова Минервы включила в себя следующие этапы:

Механическое объединение архивов В.В.Файера и Н.В. Брагинской в одной директории.
Создание списка файлов, входящих в данный архив.
Выявление дубликатов видео (1 этап сверки (имя, размер)).
Выявление дубликатов видео (2 этап (сопоставление контрольных сумм файлов, Get-FileHash)).
Приведение файлов к единому формату данных (унификация видеоматериалов, перекодировка в формат MP4).
Создание отсутствующих расшифровок записей, их включение в архив.
